name: "Systemtests-prepare-env"
description: "Prepare environment for system tests"

inputs:
  releaseVersion:
    description: "Release version to test (i.e. 'latest', '0.46.0')"
    required: false
    default: "latest"
  architecture:
    description: "Architecture (amd64, arm64)"
    required: false
    default: "amd64"
  ref:
    description: "Git ref for conditional logic"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.9
    - uses: actions/setup-java@v5
      with:
        distribution: "temurin"
        java-version: "17"
        cache: 'maven'

    - name: Install Helm
      uses: ./.github/actions/install-helm

    - name: Install Shellcheck
      uses: ./.github/actions/install-shellcheck
      with:
        architecture: ${{ matrix.config.arch }}
    - name: Install yq
      uses: ./.github/actions/install-yq
      with:
        architecture: ${{ matrix.config.arch }}

    - name: Install Docker
      uses: ./.github/actions/install-docker

    - name: Install Kind
      uses: ./.github/actions/setup-kind
      with:
        architecture: ${{ matrix.config.arch }}
        # Could be overriden per pipeline
        controlNodes: 1
        workerNodes: 1

    - name: Set default environment variables
      uses: ./.github/actions/set-defaults

    - name: Set release version
      if: ${{ inputs.releaseVersion != 'latest' }}
      shell: bash
      run: |
        echo "RELEASE_VERSION=${{ inputs.releaseVersion }}" >> $GITHUB_ENV

    - name: Set DOCKER_TAG to releaseVersion
      if: ${{ inputs.releaseVersion != 'latest' }}
      shell: bash
      run: |
        echo "DOCKER_TAG=${{ inputs.releaseVersion }}" >> $GITHUB_ENV

    - name: Set DOCKER_REGISTRY to quay.io if releaseVersion != latest
      if: ${{ inputs.releaseVersion != 'latest' }}
      shell: bash
      run: |
        echo "DOCKER_REGISTRY=quay.io" >> $GITHUB_ENV

    - name: Set ST_KAFKA_VERSION if kafkaVersion != latest
      if: ${{ env.KAFKA_VERSION != 'latest' }}
      shell: bash
      run: |
        echo "ST_KAFKA_VERSION=${KAFKA_VERSION}" >> $GITHUB_ENV

    - name: Print out environment info
      uses: ./.github/actions/log-variables

    # Load Strimzi images
    - name: Load Strimzi images
      if: ${{ env.DOCKER_TAG == 'latest' && inputs.ref != 'main' }}
      uses: ./.github/actions/containers-load
      with:
        architecture: ${{ inputs.architecture }}
        registry: "kind"

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: "maven-cache | **/pom.xml"
        restore-keys: |
          maven | ${{ github.job }}
          maven

    # Build Strimzi without images => used when running the STs against releases or release candidates where the images
    # are already built, and we need only the Java build
    - name: Build Strimzi Java code
      shell: bash
      run: make java_install
      env:
        MVN_ARGS: "-DskipTests -Dmaven.javadoc.skip=true  -e -V -B"

    - name: Create dir for Kafka binaries cache
      if: ${{ env.DOCKER_TAG != 'latest' }}
      shell: bash
      run: mkdir -p docker-images/artifacts/binaries/kafka/archives

    ############################################################################
    # Build KafkaConnect image with file-sink plugin, skipping if "upgrade"
    ############################################################################
    - name: Build KafkaConnect image
      # we want to let Connect image build for different versions of Kafka inside the upgrade/downgrade STs
      if: ${{ !contains(env.PROFILE, 'upgrade') }}
      shell: bash
      run: |
        CONNECT_IMAGE="${DOCKER_REGISTRY}/${DOCKER_ORG}/connect-file-sink:latest"
        KAFKA_VERSION=$([[ "${KAFKA_VERSION}" == *"latest"* ]] && yq eval '.[] | select(.default) | .version' kafka-versions.yaml || echo "${KAFKA_VERSION}")
        BASE_IMAGE="${DOCKER_REGISTRY}/${DOCKER_ORG}/kafka:${DOCKER_TAG}-kafka-${KAFKA_VERSION}"
        
        echo "Base image: $BASE_IMAGE"
        eval "$(./systemtest/src/test/resources/connect-build/build-connect-image.sh "$KAFKA_VERSION" "$BASE_IMAGE" "$CONNECT_IMAGE")"
        echo "connect build image: $CONNECT_IMAGE_WITH_FILE_SINK_PLUGIN"
        
        # Push the images
        docker push ${CONNECT_IMAGE_WITH_FILE_SINK_PLUGIN}
        
        # Provide "connectImage" variable for tests:
        echo "CONNECT_IMAGE_WITH_FILE_SINK_PLUGIN=${CONNECT_IMAGE_WITH_FILE_SINK_PLUGIN}" >> $GITHUB_ENV

    ############################################################################
    # We need to set DOCKER_REGISTRY to IP and port of service, which is created by minikube registry addon, port is always 80
    # Default value for PRs is localhost:5000 because we need to push built images into minikube registry and make them available for pods
    ############################################################################
    - name: "Set docker_registry to local registry in minikube"
      if: ${{ contains(env.DOCKER_REGISTRY, 'localhost:5000') }}
      shell: bash
      run: |
        echo "DOCKER_REGISTRY=$(kubectl get service registry -n kube-system -o=jsonpath='{.spec.clusterIP}'):80" >> $GITHUB_ENV

    ############################################################################
    # Additional "setup_upgrade.sh" if profile includes "upgrade"
    ############################################################################
    - name: Setup environment for upgrade
      if: ${{ contains(env.PROFILE, 'upgrade') }}
      shell: bash
      run: |
        .azure/scripts/setup_upgrade.sh

    ############################################################################
    # Set KAFKA_TIERED_STORAGE_BASE_IMAGE for Tiered Storage tests
    ############################################################################
    - name: Set KAFKA_TIERED_STORAGE_BASE_IMAGE
      shell: bash
      run: |
        KAFKA_VERSION=$([[ "${KAFKA_VERSION}" == *"latest"* ]] && yq eval '.[] | select(.default) | .version' kafka-versions.yaml || echo "${KAFKA_VERSION}")
        echo "KAFKA_TIERED_STORAGE_BASE_IMAGE=${DOCKER_REGISTRY}/${DOCKER_ORG}/kafka:${DOCKER_TAG}-kafka-${KAFKA_VERSION}" >> $GITHUB_ENV

    - name: Print out environment info
      uses: ./.github/actions/log-variables
