# Triggers
trigger:
  branches:
    include:
      - 'azure-pipelines-pr-test'
#pr:
#  branches:
#    include:
#      - '*'

strategy:
  matrix:
    'java-8':
      image: 'Ubuntu-18.04'
      jdk_version: '1.8'
      jdk_path: '/usr/lib/jvm/zulu-8-azure-amd64'
    'java-11':
      image: 'Ubuntu-18.04'
      jdk_version: '11'
      jdk_path: '/usr/lib/jvm/zulu-11-azure-amd64'
#      jdk_path: '/usr/lib/jvm/java-1.11.0-openjdk-amd64'

# Base system
pool:
  vmImage: $(image)

# Environment variables
variables:
  - template: "templates/default_variables.yaml"

# Pipeline steps
steps:
  - bash: |
      echo "##vso[task.setvariable variable=JAVA_HOME]$(jdk_path)"
      echo "##vso[task.setvariable variable=JAVA_HOME__X64]$(jdk_path)"
      echo "##vso[task.setvariable variable=PATH]$(jdk_path)/bin:$(PATH)"
    displayName: 'Setup JAVA_HOME'

  - template: "templates/log_variables.yaml"

  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.4'
      addToPath: true

  - bash: gem install asciidoctor
    displayName: 'Install asciidoctor'

  - bash: ".azure/scripts/setup_docker.sh"
    displayName: "Setup Docker environment"

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'
      jdkArchitectureOption: 'x64'
      goals: 'install'
      options: '-DskipTests -q -Dmaven.javadoc.skip=true -B -V'
    displayName: 'Build Strimzi project'

  - bash: ".travis/install_yq.sh"
    displayName: "Install yq"

  - bash: ".travis/setup-kubernetes.sh"
    displayName: "Setup Minikube cluster"

  - bash: ".travis/build.sh"
    env:
      DOCKER_USER: $(DOCKER_USER)
      DOCKER_PASS: $(DOCKER_PASS_SECRET)
    displayName: "Build images"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: "Unit & Integration tests"
    condition: always()



