# Triggers
trigger:
  branches:
    include:
      # TODO change to master
      - 'azure-pipelines'
      - 'release-*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

strategy:
  matrix:
    'java-8':
      image: 'Ubuntu-18.04'
      jdk_version: '1.8'
      jdk_path: '/usr/lib/jvm/zulu-8-azure-amd64'
    'java-11':
      image: 'Ubuntu-18.04'
      jdk_version: '11'
      jdk_path: '/usr/lib/jvm/zulu-11-azure-amd64'

# Base system
pool:
  vmImage: $(image)

# Environment variables
variables:
  - template: "templates/default_variables.yaml"

# Pipeline steps
steps:
  - template: 'templates/setup_java.yaml'
    parameters:
      JDK_PATH: $(jdk_path)

  - template: "templates/log_variables.yaml"

  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.4'
      addToPath: true

  - bash: gem install asciidoctor
    displayName: 'Install asciidoctor'

  - bash: ".azure/scripts/setup_docker.sh"
    displayName: "Setup Docker environment"

  - template: "templates/build_strimzi.yaml"

  - bash: ".travis/install_yq.sh"
    displayName: "Install yq"

  - bash: ".travis/setup-kubernetes.sh"
    displayName: "Setup Minikube cluster"

  - bash: ".travis/build.sh"
    env:
      DOCKER_USER: $(DOCKER_USER)
      DOCKER_PASS: $(DOCKER_PASS_SECRET)
    displayName: "Build images"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: "Unit & Integration tests"
    condition: always()



