# Triggers
# This pipeline will be trigger by github command /azp pull-request-pipeline
trigger: none
pr:
  autoCancel: true
  branches:
    include:
      - '*'

# Base system
pool:
  vmImage: 'Ubuntu-18.04'

# Environment variables
variables:
  pull_request: true
  docker_tag: latest
  docker_org: strimzi
  docker_registry: docker.io
  test_cluster: minikube
  test_kubectl_version: v1.15.0
  test_nsenter_version: 2.32
  test_helm_version: v2.9.1
  test_minikube_version: v1.2.0
  strimzi_default_log_level: DEBUG
  docker_build_args: "-q"

# Pipeline steps
steps:
# Docker installed via this task is not available under root
#  - task: DockerInstaller@0
#    displayName: Docker Installer
#    inputs:
#      dockerVersion: 19.03.5
#      releaseType: stable

  - bash: ".azure/scripts/setup_docker.sh"
    displayName: "Setup Docker environment"

  - bash: ".travis/setup-kubernetes.sh"
    displayName: "Setup Minikube cluster"

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/failsafe-reports/TEST-*.xml'
      goals: 'install'
      options: '-DskipTests -q -Dmaven.javadoc.skip=true -B -V'
    displayName: 'Build Strimzi project'

  - task: Maven@3
    inputs:
      mavenPomFile: 'systemtest/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/failsafe-reports/TEST-*.xml'
      goals: 'verify'
      options: '-Dgroups=travis -Dmaven.javadoc.skip=true -B -V'
    displayName: 'Run systemtests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/TEST-*.xml'
      searchFolder: "systemtest"
      testRunTitle: "System tests"
    condition: always()



