# Triggers
# This pipeline will be trigger by github command /azp pull-request-pipeline
trigger: none
pr:
  autoCancel: true
  branches:
    include:
      - '*'

# Base system
pool:
  vmImage: 'Ubuntu-18.04'

# Environment variables
variables:
  - template: 'templates/default_variables.yaml'

# Pipeline steps
steps:
  - template: 'templates/setup_java.yaml'

  - template: "templates/log_variables.yaml"

  - bash: ".azure/scripts/setup_docker.sh"
    displayName: "Setup Docker environment"

  - bash: ".travis/install_yq.sh"
    displayName: "Install yq"

  - bash: ".travis/setup-kubernetes.sh"
    displayName: "Setup Minikube cluster"

  - template: "templates/build_strimzi.yaml"

  - bash: |
      make docker_build
      make docker_tag
    displayName: "Build Strimzi images locally"

  - task: Maven@3
    inputs:
      mavenPomFile: 'systemtest/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/failsafe-reports/TEST-*.xml'
      goals: 'verify'
      options: '-Dgroups=travis -Dmaven.javadoc.skip=true -B -V'
    env:
      OPERATOR_IMAGE_PULL_POLICY: "IfNotPresent"
    displayName: 'Run systemtests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/TEST-*.xml'
      searchFolder: "systemtest"
      testRunTitle: "System tests"
    condition: always()



