# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'
      -
# Regression tests are split into 6 jobs because of timeout set to 360 minutes for each job
jobs:
  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_kafka'
      display_name: 'regression-bundle I. - kafka'
      test_case: 'OauthTlsST,OauthAuthorizationST,OauthPlainST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360
