# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

stages:
  - stage:

    jobs:
      - job: Say start
        displayName: 'Test pipelines trigger'
        steps:
          - script: echo "Starting uploading Skynet ..."
            displayName: "Trigger all jobs"
  - stage:
      jobs:
        - template: 'templates/system_test_general.yaml'
          parameters:
            name: 'acceptance_helm'
            display_name: 'acceptance-helm'
            test_case: '.*ST'
            groups: 'acceptance'
            cluster_operator_install_type: 'helm'
            timeout: 240

        - template: 'templates/system_test_general.yaml'
          parameters:
            name: 'acceptance_helm_namespace_rbac_scope'
            display_name: 'acceptance-helm-namespace-rbac-scope'
            test_case: '.*ST'
            groups: 'acceptance'
            cluster_operator_install_type: 'helm'
            strimzi_rbac_scope: NAMESPACE
            timeout: 240

        - template: 'templates/system_test_general.yaml'
          parameters:
            name: 'acceptance'
            display_name: 'acceptance-bundle'
            test_case: '.*ST'
            groups: 'acceptance'
            cluster_operator_install_type: 'bundle'
            timeout: 240



