# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

stages:
  - stage: "precheck"
    jobs:
      - job: "build_strimzi"
        displayName: 'Build Strimzi'
        steps:
          - template: "build_strimzi.yaml"

  - stage: "acceptance"
    dependsOn: ["precheck"]
    jobs:
      - template: 'templates/system_test_general.yaml'
        parameters:
          name: 'acceptance_helm'
          display_name: 'acceptance-helm'
          test_case: '.*ST'
          groups: 'acceptance'
          cluster_operator_install_type: 'helm'
          timeout: 240

      - template: 'templates/system_test_general.yaml'
        parameters:
          name: 'acceptance_helm_namespace_rbac_scope'
          display_name: 'acceptance-helm-namespace-rbac-scope'
          test_case: '.*ST'
          groups: 'acceptance'
          cluster_operator_install_type: 'helm'
          strimzi_rbac_scope: NAMESPACE
          timeout: 240

      - template: 'templates/system_test_general.yaml'
        parameters:
          name: 'acceptance'
          display_name: 'acceptance-bundle'
          test_case: '.*ST'
          groups: 'acceptance'
          cluster_operator_install_type: 'bundle'
          timeout: 240

  - stage: "upgrade"
    dependsOn: ["precheck"]
    jobs:
      - template: 'templates/system_test_general.yaml'
        parameters:
          name: 'strimzi_upgrade'
          display_name: 'strimzi-upgrade-bundle'
          test_case: 'upgrade/**/*ST,!KafkaUpgradeDowngradeST'
          groups: 'upgrade'
          cluster_operator_install_type: 'bundle'
          timeout: 360

      - template: 'templates/system_test_general.yaml'
        parameters:
          name: 'kafka_upgrade_downgrade'
          display_name: 'kafka-upgrade-downgrade-bundle'
          test_case: 'KafkaUpgradeDowngradeST'
          groups: 'upgrade'
          cluster_operator_install_type: 'bundle'
          timeout: 360

  - stage: "regression"
    dependsOn: ["acceptance"]
    jobs:
      - template: "templates/regression_jobs.yaml"

  - stage: "feature_gates_regression"
    dependsOn: [ "acceptance" ]
    jobs:
      - template: "templates/feature_gates_regression_jobs.yaml"



