# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

stages:
#  - stage: "precheck"
#    jobs:
#      - job: "trigger"
#        displayName: 'Dummy trigger'
#        steps:
#          - script: echo "Starting uploading Skynet ..."
#            displayName: "Dummy trigger"
#
#  - stage: "acceptance"
#    dependsOn: [ "precheck" ]
#    jobs:
#      - template: 'templates/jobs/acceptance_helm_jobs.yaml'
#
#      - template: 'templates/jobs/acceptance_helm_namespace_rbac_jobs.yaml'
#
#      - template: 'templates/jobs/acceptance_jobs.yaml'
#
#  - stage: "upgrade"
#    dependsOn: [ "precheck" ]
#    jobs:
#      - template: 'templates/jobs/upgrade_jobs.yaml'
#
#  - stage: "regression"
#    dependsOn: [ "acceptance","upgrade" ]
#    jobs:
#      - template: "templates/jobs/regression_jobs.yaml"
#
#  - stage: "regression_feature_gates"
#    dependsOn: [ "acceptance","regression","upgrade" ]
#    condition: always()
#    jobs:
#      - template: "templates/jobs/feature_gates_regression_jobs.yaml"
#
#  - stage: "regression_namespace_rbac"
#    dependsOn: [ "acceptance","regression","upgrade","regression_feature_gates" ]
#    condition: always()
#    jobs:
#      - template: "templates/jobs/regression_namespace_rbac_jobs.yaml"

  - stage: "precheck"
    jobs:
      - job: "trigger"
        displayName: 'Dummy trigger'
        steps:
          - script: echo "Starting uploading Skynet ..."
            displayName: "Dummy trigger"

  - stage: "acceptance"
    dependsOn: [ "precheck" ]
    jobs:
      - job:
        steps:
          - script: exit 0

  - stage: "upgrade"
    dependsOn: [ "precheck" ]
    jobs:
      - job:
        steps:
          - script: exit 1

  - stage: "regression"
    dependsOn: [ "acceptance","upgrade" ]
    jobs:
      - job:
        steps:
          - script: exit 0

  - stage: "regression_feature_gates"
    dependsOn: [ "acceptance","regression","upgrade" ]
    condition: always()
    jobs:
      - job:
        steps:
          - script: exit 0

  - stage: "regression_namespace_rbac"
    dependsOn: [ "acceptance","regression","upgrade","regression_feature_gates" ]
    condition: always()
    jobs:
      - job:
        steps:
          - script: exit 0



