# Triggers
# This pipeline will be trigger manually for releases
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

jobs:
  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'upgrade'
      display_name: 'upgrade-bundle'
      test_case: '.*ST'
      groups: 'upgrade'
      cluster_operator_install_type: 'bundle'
      timeout: 240


