apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-sub
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: strimzi
spec:
  name: strimzi
  source: strimzi-source
  sourceNamespace: ${OPERATOR_NAMESPACE}
  startingCSV: ${APP_BUNDLE_PREFIX}.${OLM_VERSION}
  channel: ${OLM_PACKAGE_CHANNEL}
