name: Run System Tests

on:
  workflow_call:
    inputs:
      profileList:
        description: "Comma-separated or single profile name(s)"
        required: false
        default: ""
        type: string
      pipelineList:
        description: "Comma-separated or single pipeline name(s)"
        required: false
        default: ""
        type: string
      excludedGroups:
        description: "Excluded groups"
        required: false
        default: ""
        type: string
      cluster_operator_install_type:
        description: "Install type method used for Strimzi operator"
        required: false
        default: "yaml"
        type: string
      strimzi_rbac_scope:
        description: "RBAC configuration for operator access"
        required: false
        default: "CLUSTER"
        type: string
      parallel:
        description: "How many tests should be executed in parallel"
        required: false
        default: "1"
        type: string
      strimzi_feature_gates:
        description: "Which feature-gates will be used by operator"
        required: false
        default: ""
        type: string
      releaseVersion:
        description: "Release version to test (i.e. 'latest', '0.46.0')"
        required: false
        default: "latest"
        type: string
      kafkaVersion:
        description: "Kafka version. e.g. '4.0.0' or 'latest'"
        required: false
        default: "latest"
        type: string
      agent:
        description: "On which agent the jobs will be executed"
        required: true
        type: string
      architecture:
        description: "Which architecture is used for the job"
        required: true
        type: string
      groups:
        description: "JUnit5 test groups that will be executed"
        required: false
        # Empty string means all groups
        default: ""
        type: string
      tests:
        description: "JUnit5 tests that will be executed"
        required: false
        # Empty string means all tests
        default: ""
        type: string
      kubeVersion:
        description: "Used Kubernetes version for Kind/Minikube. Note that for Kind you have to use whole image with sha digest!"
        required: false
        # Empty string means it will use default from setup scripts
        default: ""
        type: string
      # Checkout ref params
      ref:
        description: "Repository ref that will be checkout"
        required: true
        type: string

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - name: Generate Matrix
        id: gen
        uses: ./.github/actions/generate-matrix
        with:
          pipelines: ${{ inputs.pipelineList }}
          profiles: ${{ inputs.profileList }}
          default_agent: ${{ inputs.agent }}
          default_arch: ${{ inputs.architecture }}
          default_strimzi_feature_gates: ${{ inputs.strimzi_feature_gates }}
          default_strimzi_rbac_scope: ${{ inputs.strimzi_rbac_scope }}
          default_cluster_operator_install_type: ${{ inputs.cluster_operator_install_type }}
          default_parallel: ${{ inputs.parallel }}
          runnerArch: "amd64"

  run-tests:
    needs: generate-matrix
    strategy:
      matrix:
        config: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    # Max timeout ise set for 10h for the whole job, test execution has lower timeouts to not block the job for the whole time
    # but have some additional time to collect logs, etc.
    timeout-minutes: 600
    name: ${{ matrix.config.jobName }}
    runs-on: ${{ matrix.config.agent }}
    # Environment variables
    env:
      KAFKA_VERSION: ${{ inputs.kafkaVersion }}
      DOCKER_TAG: ${{ inputs.releaseVersion }}
      PROFILE: ${{ matrix.config.profile }}
      ARCH: ${{ matrix.config.architecture }}
      STRIMZI_RBAC_SCOPE: ${{ matrix.config.strimzi_rbac_scope }}
      CLUSTER_OPERATOR_INSTALL_TYPE: ${{ matrix.config.cluster_operator_install_type }}
      STRIMZI_FEATURE_GATES: ${{ matrix.config.strimzi_use_feature_gates }}
      PARALLEL: ${{ matrix.config.parallel }}
      STRIMZI_DEFAULT_LOG_LEVEL: DEBUG
      OPERATOR_IMAGE_PULL_POLICY: IfNotPresent
      COMPONENTS_IMAGE_PULL_POLICY: IfNotPresent
      # Kube version for Kind
      KIND_NODE_IMAGE: ${{ inputs.kubeVersion }}
      # Kube version for Minikube
      KUBE_VERSION: ${{ inputs.kubeVersion }}
    # Job steps
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}

      - name: Set check & commit status
        uses: ./.github/actions/check-and-status
        with:
          checkState: pending
          checkName: ${{ matrix.config.jobName }}
          checkDescription: "Test run for ${{ matrix.config.jobName }}"

      - name: Prepare systemtests env
        uses: ./.github/actions/systemtests/prepare-env
        with:
          architecture: ${{ matrix.config.arch }}
          releaseVersion: ${{ inputs.releaseVersion }}
          ref: ${{ inputs.ref }}

      ############################################################################
      # Run system tests
      ############################################################################
      - name: Run & archive
        uses: ./.github/actions/systemtests/run
        with:
          agent: ${{ matrix.config.agent }}
          pipeline: ${{ matrix.config.pipeline }}
          profile: ${{ matrix.config.profile }}
          groups: ${{ inputs.groups }}
          tests: ${{ inputs.tests }}
          excludedGroups: ${{ inputs.excludedGroups }}
          parallel: ${{ inputs.parallel }}

      - name: Set check & commit status
        if: ${{ always() }}
        uses: ./.github/actions/check-and-status
        with:
          checkState: ${{ steps.run_tests.conclusion }}
          checkName: ${{ matrix.config.jobName }}
          checkDescription: "Test run for ${{ matrix.config.jobName }}"
